---
output: pdf_document
params:
  pessoa: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

---
title: `r params$pessoa`
---

```{r}
library(dplyr)
library(gghighlight)

filmes_da_pessoa <- basesCursoR::pegar_base("imdb") %>% 
  mutate(
    data_lancamento = as.Date(data_lancamento) 
  ) %>%  
  filter(
    stringr::str_detect(direcao, params$pessoa) |
      stringr::str_detect(elenco, params$pessoa)
  )
```

## O que assistir?

```{r}
nota_dos_melhores_filmes <- quantile(filmes_da_pessoa$nota_imdb, .9)

tab_melhores <- filmes_da_pessoa %>% 
  filter(nota_imdb >= nota_dos_melhores_filmes) %>% 
  select(data_lancamento, titulo_original, nota_imdb) %>% 
  arrange(desc(nota_imdb))
```

Os filmes mais adorados: `r paste(tab_melhores$titulo_original, collapse = ", ")`.

## O que não assistir?

```{r}
nota_dos_piores_filmes <- quantile(filmes_da_pessoa$nota_imdb, .1)

tab_piores <- filmes_da_pessoa %>% 
  filter(nota_imdb <= nota_dos_piores_filmes) %>% 
  select(data_lancamento, titulo_original, nota_imdb, num_avaliacoes) %>% 
  arrange(desc(nota_imdb))
```

Os filmes mais odiados: `r paste(tab_piores$titulo_original, collapse = ", ")`.

```{r, fig.height=7, fig.width=8}
filmes_da_pessoa %>% 
  filter(nota_imdb > nota_dos_piores_filmes, nota_imdb < nota_dos_melhores_filmes) %>% 
  ggplot(aes(x = data_lancamento, y = nota_imdb)) + 
  geom_point(color = "grey") + 
  geom_smooth(se = FALSE, color = "grey") +
  geom_point(data = tab_melhores, color = "dark green") + 
  geom_smooth(data = tab_melhores, se = FALSE, color = "dark green") +
  ggrepel::geom_label_repel(data = tab_melhores, aes(label = titulo_original), color = "dark green") + 
  geom_point(data = tab_piores, color = "red") + 
  geom_smooth(data = tab_piores, se = FALSE, color = "red") +
  ggrepel::geom_label_repel(data = tab_piores, aes(label = titulo_original), color = "red") + 
  theme(
    legend.position = 'none'
  ) +
  theme_minimal() + 
  labs(
    x = "Noda média no IMDB",
    y = "Nota média no ano"
  ) +
  scale_y_continuous(limits = c(0, 10))
```

\newpage

## Lista de filmes

```{r}
filmes_da_pessoa %>% 
  arrange(desc(nota_imdb)) %>% 
  select(
    Ano = ano, 
    `Título` = titulo_original,
    Nota = nota_imdb
  ) %>% 
  knitr::kable()
```

